/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g,m=this||self;function p(){}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function aa(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}
function ca(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function t(a,b,c){t=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return t.apply(null,arguments)}
function u(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a};var v;var da=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ea=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
function fa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ha=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},ia=/&/g,ja=/</g,ka=/>/g,la=/"/g,ma=/'/g,na=/\x00/g,oa=/[\x00&<>"']/;function w(a,b){return a<b?-1:a>b?1:0};var x;a:{var pa=m.navigator;if(pa){var qa=pa.userAgent;if(qa){x=qa;break a}}x=""};function ra(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function sa(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return!0;return!1}var ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ua(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ta.length;f++)c=ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function y(){this.va=""}y.prototype.u=!0;y.prototype.o=function(){return this.va.toString()};y.prototype.f=function(a){this.va=a;return this};(new y).f("");function z(a,b){this.ya=a===va&&b||"";this.Da=wa}z.prototype.u=!0;z.prototype.o=function(){return this.ya.toString()};var xa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,wa={},va={};function A(){this.xa=""}A.prototype.u=!0;A.prototype.o=function(){return this.xa};A.prototype.f=function(a){this.xa=a;return this};(new A).f("");function B(){this.wa=""}B.prototype.u=!0;B.prototype.o=function(){return this.wa};B.prototype.f=function(a){this.wa=a;return this};(new B).f("");function C(){this.ua=""}C.prototype.u=!0;C.prototype.o=function(){return this.ua.toString()};C.prototype.f=function(a){this.ua=a;return this};(new C).f("<!DOCTYPE html>",0);(new C).f("",0);(new C).f("<br>",0);function ya(a,b){b?a=a.replace(ia,"&amp;").replace(ja,"&lt;").replace(ka,"&gt;").replace(la,"&quot;").replace(ma,"&#39;").replace(na,"&#0;"):oa.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(ia,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(ja,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(ka,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(la,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(ma,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(na,"&#0;")));return a};function D(a){D[" "](a);return a}D[" "]=p;function za(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var Aa=-1!=x.indexOf("Opera"),E=-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE"),Ba=-1!=x.indexOf("Edge"),Ca=-1!=x.indexOf("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&-1==x.indexOf("Edge"))&&!(-1!=x.indexOf("Trident")||-1!=x.indexOf("MSIE"))&&-1==x.indexOf("Edge"),F=-1!=x.toLowerCase().indexOf("webkit")&&-1==x.indexOf("Edge");function Da(){var a=m.document;return a?a.documentMode:void 0}var G;
a:{var Ea="",Fa=function(){var a=x;if(Ca)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ba)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(F)return/WebKit\/(\S+)/.exec(a);if(Aa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Fa&&(Ea=Fa?Fa[1]:"");if(E){var Ga=Da();if(null!=Ga&&Ga>parseFloat(Ea)){G=String(Ga);break a}}G=Ea}var Ha=G,Ia={};
function Ja(a){return za(Ia,a,function(){for(var b=0,c=ha(String(Ha)).split("."),d=ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=w(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||w(0==h[2].length,0==k[2].length)||w(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var Ka;
if(m.document&&E){var La=Da();Ka=La?La:parseInt(Ha,10)||void 0}else Ka=void 0;var Ma=Ka;var Na=!E||9<=Number(Ma);function Oa(a,b){ra(b,function(c,d){c&&"object"==typeof c&&c.u&&(c=c.o());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Pa.hasOwnProperty(d)?a.setAttribute(Pa[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Pa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Qa(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!aa(f)||r(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(r(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==q(f)){h="function"==typeof f.item;break a}}h=!1}ea(h?fa(f):f,e)}}}function Ra(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}
function H(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Sa(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ta(a){return a.contentDocument||a.contentWindow.document}function I(a){this.l=a||m.document||document}g=I.prototype;g.getElementsByTagName=function(a,b){return(b||this.l).getElementsByTagName(String(a))};
g.a=function(a,b,c){var d=this.l,e=arguments,f=String(e[0]),h=e[1];if(!Na&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',ya(h.name),'"');if(h.type){f.push(' type="',ya(h.type),'"');var k={};ua(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=Ra(d,f);h&&("string"===typeof h?f.className=h:Array.isArray(h)?f.className=h.join(" "):Oa(f,h));2<e.length&&Qa(d,f,e,2);return f};g.createElement=function(a){return Ra(this.l,a)};g.createTextNode=function(a){return this.l.createTextNode(String(a))};
g.ja=function(){var a=this.l;return a.parentWindow||a.defaultView};g.appendChild=function(a,b){a.appendChild(b)};g.append=function(a,b){Qa(Sa(a),a,arguments,1)};g.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function J(){this.M=this.M;this.W=this.W}J.prototype.M=!1;J.prototype.Ha=function(){this.M||(this.M=!0,this.i())};J.prototype.i=function(){if(this.W)for(;this.W.length;)this.W.shift()()};var Ua=!E||9<=Number(Ma),Va=E&&!Ja("9"),Wa=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",p,b),m.removeEventListener("test",p,b)}catch(c){}return a}();function K(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.j=!1}K.prototype.stopPropagation=function(){this.j=!0};K.prototype.preventDefault=function(){this.defaultPrevented=!0};function L(a,b){K.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.m=null;a&&this.La(a,b)}u(L,K);var Xa={2:"touch",3:"pen",4:"mouse"};
L.prototype.La=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Ca){a:{try{D(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=
d.screenY||0):(this.offsetX=F||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=F||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=
a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Xa[a.pointerType]||"";this.state=a.state;this.m=a;a.defaultPrevented&&this.preventDefault()};L.prototype.stopPropagation=function(){L.I.stopPropagation.call(this);this.m.stopPropagation?this.m.stopPropagation():this.m.cancelBubble=!0};
L.prototype.preventDefault=function(){L.I.preventDefault.call(this);var a=this.m;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Va)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Ya="closure_listenable_"+(1E6*Math.random()|0);function M(a){return!(!a||!a[Ya])}var Za=0;function $a(a,b,c,d,e,f){this.listener=a;this.Y=b;this.src=c;this.type=d;this.capture=!!e;this.R=f;this.key=++Za;this.w=this.L=!1}$a.prototype.V=function(){this.w=!0;this.R=this.src=this.Y=this.listener=null};function N(a){this.src=a;this.b={};this.J=0}g=N.prototype;g.add=function(a,b,c,d,e){var f=a.toString();a=this.b[f];a||(a=this.b[f]=[],this.J++);var h=ab(a,b,d,e);-1<h?(b=a[h],c||(b.L=!1)):(b=new $a(b,null,this.src,f,!!d,e),b.L=c,a.push(b));return b};g.remove=function(a,b,c,d){a=a.toString();if(!(a in this.b))return!1;var e=this.b[a];b=ab(e,b,c,d);return-1<b?(e[b].V(),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.b[a],this.J--),!0):!1};
g.za=function(a){var b=a.type;if(!(b in this.b))return!1;var c=this.b[b],d=da(c,a),e;(e=0<=d)&&Array.prototype.splice.call(c,d,1);e&&(a.V(),0==this.b[b].length&&(delete this.b[b],this.J--));return e};g.da=function(a){a=a&&a.toString();var b=0,c;for(c in this.b)if(!a||c==a){for(var d=this.b[c],e=0;e<d.length;e++)++b,d[e].V();delete this.b[c];this.J--}return b};g.G=function(a,b,c,d){a=this.b[a.toString()];var e=-1;a&&(e=ab(a,b,c,d));return-1<e?a[e]:null};
g.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return sa(this.b,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function ab(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.w&&f.listener==b&&f.capture==!!c&&f.R==d)return e}return-1};var bb="closure_lm_"+(1E6*Math.random()|0),cb={},db=0;function O(a,b,c,d,e){if(d&&d.once)return P(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)O(a,b[f],c,d,e);return null}c=Q(c);return M(a)?a.g(b,c,r(d)?!!d.capture:!!d,e):eb(a,b,c,!1,d,e)}
function eb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=r(e)?!!e.capture:!!e,k=R(a);k||(a[bb]=k=new N(a));c=k.add(b,c,d,h,f);if(c.Y)return c;d=fb();c.Y=d;d.src=a;d.listener=c;if(a.addEventListener)Wa||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(gb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");db++;return c}
function fb(){var a=hb,b=Ua?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function P(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)P(a,b[f],c,d,e);return null}c=Q(c);return M(a)?a.oa(b,c,r(d)?!!d.capture:!!d,e):eb(a,b,c,!0,d,e)}
function ib(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)ib(a,b[f],c,d,e);return null}d=r(d)?!!d.capture:!!d;c=Q(c);if(M(a))return a.ga(b,c,d,e);if(!a)return!1;if(a=R(a))if(b=a.G(b,c,d,e))return S(b);return!1}
function S(a){if("number"===typeof a||!a||a.w)return!1;var b=a.src;if(M(b))return b.Ca(a);var c=a.type,d=a.Y;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(gb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);db--;(c=R(b))?(c.za(a),0==c.J&&(c.src=null,b[bb]=null)):a.V();return!0}function gb(a){return a in cb?cb[a]:cb[a]="on"+a}
function jb(a,b,c,d){var e=!0;if(a=R(a))if(b=a.b[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.w&&(f=kb(f,d),e=e&&!1!==f)}return e}function kb(a,b){var c=a.listener,d=a.R||a.src;a.L&&S(a);return c.call(d,b)}
function hb(a,b){if(a.w)return!0;if(!Ua){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new L(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.currentTarget;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.j&&0<=e;e--){b.currentTarget=d[e];var f=jb(d[e],a,!0,b);c=c&&f}for(e=0;!b.j&&e<d.length;e++)b.currentTarget=
d[e],f=jb(d[e],a,!1,b),c=c&&f}return c}return kb(a,new L(b,this))}function R(a){a=a[bb];return a instanceof N?a:null}var lb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Q(a){if("function"==q(a))return a;a[lb]||(a[lb]=function(b){return a.handleEvent(b)});return a[lb]};function T(a){J.call(this);this.s=a;this.v={}}u(T,J);var mb=[];g=T.prototype;g.g=function(a,b,c,d){return this.Oa(a,b,c,d)};g.Oa=function(a,b,c,d,e){Array.isArray(b)||(b&&(mb[0]=b.toString()),b=mb);for(var f=0;f<b.length;f++){var h=O(a,b[f],c||this.handleEvent,d||!1,e||this.s||this);if(!h)break;this.v[h.key]=h}return this};g.oa=function(a,b,c,d){return this.pa(a,b,c,d)};
g.pa=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.pa(a,b[f],c,d,e);else{a=P(a,b,c||this.handleEvent,d,e||this.s||this);if(!a)return this;this.v[a.key]=a}return this};g.ga=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.ga(a,b[f],c,d,e);else c=c||this.handleEvent,d=r(d)?!!d.capture:!!d,e=e||this.s||this,c=Q(c),d=!!d,b=M(a)?a.G(b,c,d,e):a?(a=R(a))?a.G(b,c,d,e):null:null,b&&(S(b),delete this.v[b.key]);return this};
g.da=function(){ra(this.v,function(a,b){this.v.hasOwnProperty(b)&&S(a)},this);this.v={}};g.i=function(){T.I.i.call(this);this.da()};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function nb(a,b,c,d,e,f,h){this.s=h;this.ha=this.K=null;this.A=1;this.Na=c;this.h=a?new I(Sa(a)):v||(v=new I);this.ia=new T(this);a=this.h;d=a.a("DIV",{className:"switcherOuter",style:"left:"+c+"px;top:"+d+"px;width:"+e+";height:"+f+";"});a.appendChild(b,d);this.aa=d;b=d.offsetWidth-13-2;this.N=a.a("DIV",{className:"switcherContent",style:"left:"+c+"px;top:0;width:"+(b-7-c)+"px;height:80%;"},a.a("TABLE","switcherTable",a.a("TBODY",null,this.$=a.a("TR"))));d.appendChild(this.N);this.D=a.a("DIV",{className:"switcherArrows",
style:"left:"+b+"px;top:0;width:13px;height:50%;"},a.a("B",null,">"));d.appendChild(this.D);this.C=a.a("DIV",{className:"switcherArrows",style:"left:"+b+"px;top:"+d.offsetHeight/2+"px;width:13px;height:50%;"},a.a("B",null,"<"));d.appendChild(this.C);this.ia.g(this.C,"mouseover",this.Sa).g(this.D,"mouseover",this.Ta).g(this.C,"mouseout",this.Qa).g(this.D,"mouseout",this.Ra).g(this.C,"mousedown",this.ta).g(this.D,"mousedown",this.ta);this.F=0;this.S=null}g=nb.prototype;
g.clear=function(a){if(a){a=this.$.cells.length;for(var b=0;b<a;b++)this.$.deleteCell(0)}else H(this.aa),this.aa=null};g.Ga=function(a){var b=this.$.cells.length,c=this.$;c.insertCell(b);var d=c.cells[b];H(d);d.appendChild(this.h.createTextNode(a.name));d.item=a;d=c.cells[b];d.className="switcherItem";a.initialSheet&&this.B(a,d,!1);this.ia.g(d,"click",t(this.B,this,a,d,!0));return d};g.Ea=function(a,b){null==this.K&&this.B(a,b,!1)};
g.B=function(a,b,c){a!=this.K&&(null!=this.K&&(this.ha.className="switcherItem"),this.K=a,this.ha=b,b.className="switcherItemActive",b=this.s,null!=b&&b(a,c))};g.Va=function(){var a=this.aa.offsetWidth-13-2;this.N.style.width=a-7-this.Na+"px";this.D.style.left=a+"px";this.C.style.left=a+"px"};g.Aa=function(){this.N.scrollLeft+=1*this.A*this.F};g.Sa=function(){this.A=1;this.F=-1;this.S=window.setInterval(t(this.Aa,this),10)};
g.Ta=function(){this.F=this.A=1;this.S=window.setInterval(t(this.Aa,this),10)};g.Qa=function(){window.clearInterval(this.S);this.F=0};g.Ra=function(){window.clearInterval(this.S);this.F=0};g.ta=function(){4>this.A?this.A++:this.A=1};g.cleanup=function(){this.s=null};function ob(a,b){return(new U(b)).Wa(a)}function U(a){this.Z=a}U.prototype.Wa=function(a){var b=[];this.ea(a,b);return b.join("")};
U.prototype.ea=function(a,b){if(null==a)b.push("null");else{if("object"==typeof a){if(Array.isArray(a)){this.Xa(a,b);return}if(a instanceof String||a instanceof Number||a instanceof Boolean)a=a.valueOf();else{this.Za(a,b);return}}switch(typeof a){case "string":this.Ba(a,b);break;case "number":this.Ya(a,b);break;case "boolean":b.push(String(a));break;case "function":b.push("null");break;default:throw Error("Unknown type: "+typeof a);}}};
var pb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},qb=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;U.prototype.Ba=function(a,b){b.push('"',a.replace(qb,function(c){var d=pb[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),pb[c]=d);return d}),'"')};U.prototype.Ya=function(a,b){b.push(isFinite(a)&&!isNaN(a)?String(a):"null")};
U.prototype.Xa=function(a,b){var c=a.length;b.push("[");for(var d="",e=0;e<c;e++)b.push(d),d=a[e],this.ea(this.Z?this.Z.call(a,String(e),d):d,b),d=",";b.push("]")};U.prototype.Za=function(a,b){b.push("{");var c="",d;for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)){var e=a[d];"function"!=typeof e&&(b.push(c),this.Ba(d,b),b.push(":"),this.ea(this.Z?this.Z.call(a,d,e):e,b),c=",")}b.push("}")};function V(){J.call(this);this.c=new N(this);this.Fa=this;this.ca=null}u(V,J);V.prototype[Ya]=!0;g=V.prototype;g.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){ib(this,a,b,c,d)};
g.dispatchEvent=function(a){var b=this.ca;if(b){var c=[];for(var d=1;b;b=b.ca)c.push(b),++d}b=this.Fa;d=a.type||a;if("string"===typeof a)a=new K(a,b);else if(a instanceof K)a.target=a.target||b;else{var e=a;a=new K(d,b);ua(a,e)}e=!0;if(c)for(var f=c.length-1;!a.j&&0<=f;f--){var h=a.currentTarget=c[f];e=h.P(d,!0,a)&&e}a.j||(h=a.currentTarget=b,e=h.P(d,!0,a)&&e,a.j||(e=h.P(d,!1,a)&&e));if(c)for(f=0;!a.j&&f<c.length;f++)h=a.currentTarget=c[f],e=h.P(d,!1,a)&&e;return e};
g.i=function(){V.I.i.call(this);this.Ua();this.ca=null};g.g=function(a,b,c,d){return this.c.add(String(a),b,!1,c,d)};g.oa=function(a,b,c,d){return this.c.add(String(a),b,!0,c,d)};g.ga=function(a,b,c,d){return this.c.remove(String(a),b,c,d)};g.Ca=function(a){return this.c.za(a)};g.Ua=function(a){return this.c?this.c.da(a):0};
g.P=function(a,b,c){a=this.c.b[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.w&&f.capture==b){var h=f.listener,k=f.R||f.src;f.L&&this.Ca(f);d=!1!==h.call(k,c)&&d}}return d&&!c.defaultPrevented};g.G=function(a,b,c,d){return this.c.G(String(a),b,c,d)};g.hasListener=function(a,b){return this.c.hasListener(void 0!==a?String(a):void 0,b)};function W(a,b){V.call(this);this.H=a;this.la=!!b;this.na=this.ma();this.na||(this.X=O(this.H,E&&!Ja("7")?"readystatechange":"load",this.ka,!1,this),this.ba=window.setInterval(t(this.ka,this),100))}u(W,V);g=W.prototype;g.X=null;g.sa=function(){this.ba&&(window.clearInterval(this.ba),this.ba=null)};g.i=function(){delete this.H;this.sa();S(this.X);W.I.i.call(this)};g.ma=function(){var a=!1;try{if(this.la||!E||Ja("11")){var b=Ta(this.H).body;a=this.la?!!b&&!!b.firstChild:!!b}else a="complete"==this.H.readyState}catch(c){}return a};
g.ka=function(){this.ma()&&(this.sa(),S(this.X),this.X=null,this.na=!0,this.dispatchEvent("ifload"))};function rb(a,b,c,d,e,f,h,k){this.h=a?new I(Sa(a)):v||(v=new I);this.Ma=k;this.U=this.T=null;var l=this.h;f=l.a("TABLE",{style:"position:relative;left:"+c+"px;top:"+d+"px;width:"+e+";height:"+f+";",cellpadding:0,cellspacing:0},c=l.a("TBODY",null,l.a("TR",null,l.a("TD",null,e=l.a("DIV",{style:"left:0px;top:0px;width:100%;height:100%;overflow:auto"}))),l.a("TR",null,d=l.a("TD",{style:"height:26px;background-color:#eee"}))));l.appendChild(b,f);this.O=e;this.fa=a=new nb(a,d,0,0,"100%","100%",t(this.Pa,
this));k&&(k=l.a("DIV","element-link","\u00a0"),l.appendChild(c,l.a("TR",null,l.a("TD","element-link-container",k))),O(k,"click",function(){var n="http://www.google.com/webelements/";n instanceof z||(n="object"==typeof n&&n.u?n.o():String(n),xa.test(n)||(n="about:invalid#zClosurez"),n=new z(va,n));m.open(n instanceof z&&n.constructor===z&&n.Da===wa?n.ya:"type_error:SafeUrl","",void 0,void 0)}));if(h.length){l=null;for(k=0;k<h.length;k++)b=a.Ga(h[k]),0==k&&(l=b);a.Ea(h[0],l)}O(this.h.ja(),"message",
t(this.Ka,this))}g=rb.prototype;g.Pa=function(a,b){a=t(this.B,this,a,b);if("function"!=q(a))if(a&&"function"==typeof a.handleEvent)a=t(a.handleEvent,a);else throw Error("Invalid listener argument");2147483647<Number(20)||m.setTimeout(a,20)};
g.B=function(a,b){var c=a.pageUrl,d=this.O;H(d);this.U=null;var e=this.h;c=e.a("IFRAME",{id:"pageswitcher-content",style:"display: block; width: 100%; height:100%;",frameBorder:"0",marginHeight:"0",marginWidth:"0",src:c});var f=new W(c,!0);P(f,"ifload",t(this.Ia,this));e.appendChild(d,c);b&&void 0!==a.gid&&(window.location.hash="#gid="+a.gid)};g.Ia=function(a){a=a.target;this.U=a.H;a.Ha();this.T&&this.qa()};
g.Ka=function(a){a=a.m;var b=a.origin,c=b.length-11;0<=c&&b.indexOf(".google.com",c)==c&&"SendKeyboardEvents"==a.data&&(this.T=a.origin,this.ra(this.h.l),this.qa())};g.qa=function(){this.U&&this.ra(Ta(this.U))};g.ra=function(a){O(a,["keydown","keyup","keypress"],t(this.Ja,this))};g.Ja=function(a){if(this.T){var b=this.h.ja().parent;b&&b.postMessage&&b.postMessage(ob({type:a.type,ctrlKey:a.ctrlKey,altKey:a.altKey,shiftKey:a.shiftKey,metaKey:a.metaKey,keyCode:a.keyCode}),this.T)}};
g.resize=function(a,b){var c=this.O.style;c.width=a+"px";c.height=b-26-(this.Ma?24:0)+"px";this.fa.Va()};g.cleanup=function(){this.fa.cleanup();this.fa=null;H(this.O);this.O=null};function sb(a,b,c,d,e,f,h,k,l){return new rb(b,c,d,e,f,h,k,l)}var X=["_getWGTPageSwitcher"],Y=m;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===sb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=sb;
